In [1]:
!pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 29.6 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12

In [2]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [15]:
# Import Library
import pandas as pd
import numpy as np
import os

In [16]:
# Load dataset
BASE_PATH = "/content/drive/MyDrive/Nickel Mining and Smelter in Sulawesi-Maluku"

In [17]:
# Check folder
os.listdir(BASE_PATH)

['Dataset Hilirisasi - Tambang Nikel Sul-Mal Final.csv',
 'Dataset pelabuhan - Maluku.csv',
 'Dataset pelabuhan - Sulawesi.csv',
 'Dataset Mining Nickel.csv']

In [18]:
# Load mines data
mines = pd.read_csv(
    f"{BASE_PATH}/Dataset Mining Nickel.csv"
)

mines.head()

,Kecamatan,Kabupaten,Nama objek,Nomor Lokasi Keterdapatan,Komoditi,Kode Unsur,Kelompok Mineral Logam,Lokasi Keterdapatan,Provinsi,Status Penyelidikan Mineral Logam,...,AISC per Ton (Rp),CAPEX / OPEX,TRIFR,LTIFR,Jumlah Insiden,Indikator Fatalitas,Harga Nikel Historis (Rp/Ton),Nilai Tukar (Rp/USD),Pembeli / Offtaker,Jenis Kontrak
0,Malili,Luwu Timur,Nikel Desa Harapan dan Desa Pongkeru,283.000.000,Nikel,Ni,Logam Besi dan Paduan Besi,Desa Harapan dan Desa Pongkeru,Sulawesi Selatan,Operasi Produksi,...,1112412,OPEX,2.21,0.36,1,Tidak,263562245,15911,PT IWIP,FOB Motorship
1,Towuti,Luwu Timur,Nikel Limonite Sorowako,281.000.000,Nikel,Ni,Logam Besi dan Paduan Besi,Limonite Sorowako,Sulawesi Selatan,Eksplorasi,...,902738,CAPEX,1.58,0.38,1,Tidak,344250926,15541,PT GNI,CIF
2,Wasuponda,Luwu Timur,Nikel Soroako-Petea HPAL,1.921.000.000,Nikel,Ni,Logam Besi dan Paduan Besi,Soroako-Petea HPAL,Sulawesi Selatan,Eksplorasi,...,968626,CAPEX,0.51,0.29,2,Tidak,297510835,15583,PT Aneka Tambang,CIF
3,Malili,Luwu Timur,Nikel Ussu,2.136.000.000,Nikel,Ni,Logam Besi dan Paduan Besi,Ussu,Sulawesi Selatan,Operasi Produksi,...,1141389,CAPEX,1.80,0.43,1,Tidak,281917397,15809,PT IMIP,FOB Motorship
4,Malili,Luwu Timur,Nikel Blok Pongkeru dan Blok Harapan,2.816.000.000,Nikel,Ni,Logam Besi dan Paduan Besi,Blok Pongkeru dan Blok Harapan,Sulawesi Selatan,Operasi Produksi,...,903190,OPEX,2.15,0.15,0,Tidak,294606097,16044,PT IMIP,Spot Contract

In [7]:
# Load Sulawesi port
ports_sul = pd.read_csv(
    f"{BASE_PATH}/Dataset pelabuhan - Sulawesi.csv",
    sep=";"
)

ports_sul.head()

,Name,Province,UNLCODE,Latitude,Longitude,VesselInPort,ExpectedArrival,RecentPortCalls,Type
0,JAMPEA,SULAWESI SELATAN,-,-7.0581,120.6100,0,0,0,PORT
1,BENTENG,SULAWESI SELATAN,-,-6.1166,120.4512,0,0,0,PORT
2,MAKASSAR ANCH,SULAWESI SELATAN,-,-5.1195,119.3628,17,0,22,ANCHORAGE
3,MAKASSAR,SULAWESI SELATAN,IDMAK,-5.1236,119.4177,29,13,29,PORT
4,BIRINGKASSI ANCH,SULAWESI SELATAN,-,-4.8226,119.4630,9,0,3,ANCHORAGE

In [8]:
# Load Maluku port
ports_mal = pd.read_csv(
    f"{BASE_PATH}/Dataset pelabuhan - Maluku.csv",
    sep=";"
)

ports_mal.head()

,Name,Province,UNLCODE,Latitude,Longitude,VesselInPort,ExpectedArrival,RecentPortCalls,Type
0,KISAR,MALUKU,-,-8.0794,127.1479,0,0,0,PORT
1,LETI,MALUKU,-,-0.1685,127.6626,0,0,0,PORT
2,SAUMLAKI,MALUKU,IDSXK,-7.9829,131.2947,2,1,3,PORT
3,SAUMLAKI ANCH,MALUKU,-,-7.9875,131.2734,1,0,2,ANCHORAGE
4,DOBO,MALUKU,IDDOB,-5.7524,134.2115,0,0,0,PORT

In [9]:
# Merge ports
ports = pd.concat(
    [ports_sul, ports_mal],
    ignore_index=True
)

ports.head()

,Name,Province,UNLCODE,Latitude,Longitude,VesselInPort,ExpectedArrival,RecentPortCalls,Type
0,JAMPEA,SULAWESI SELATAN,-,-7.0581,120.6100,0,0,0,PORT
1,BENTENG,SULAWESI SELATAN,-,-6.1166,120.4512,0,0,0,PORT
2,MAKASSAR ANCH,SULAWESI SELATAN,-,-5.1195,119.3628,17,0,22,ANCHORAGE
3,MAKASSAR,SULAWESI SELATAN,IDMAK,-5.1236,119.4177,29,13,29,PORT
4,BIRINGKASSI ANCH,SULAWESI SELATAN,-,-4.8226,119.4630,9,0,3,ANCHORAGE

In [19]:
# Check data
print(mines.head())
print(ports.head())

   Kecamatan   Kabupaten                            Nama objek  \
0     Malili  Luwu Timur  Nikel Desa Harapan dan Desa Pongkeru
1     Towuti  Luwu Timur               Nikel Limonite Sorowako
2  Wasuponda  Luwu Timur              Nikel Soroako-Petea HPAL
3     Malili  Luwu Timur                            Nikel Ussu
4     Malili  Luwu Timur  Nikel Blok Pongkeru dan Blok Harapan

  Nomor Lokasi Keterdapatan Komoditi Kode Unsur      Kelompok Mineral Logam  \
0               283.000.000    Nikel         Ni  Logam Besi dan Paduan Besi
1               281.000.000    Nikel         Ni  Logam Besi dan Paduan Besi
2             1.921.000.000    Nikel         Ni  Logam Besi dan Paduan Besi
3             2.136.000.000    Nikel         Ni  Logam Besi dan Paduan Besi
4             2.816.000.000    Nikel         Ni  Logam Besi dan Paduan Besi

              Lokasi Keterdapatan          Provinsi  \
0  Desa Harapan dan Desa Pongkeru  Sulawesi Selatan
1               Limonite Sorowako  Sulawesi Selatan
2              Soroako-Petea HPAL  Sulawesi Selatan
3                            Ussu  Sulawesi Selatan
4  Blok Pongkeru dan Blok Harapan  Sulawesi Selatan

  Status Penyelidikan Mineral Logam  ...  AISC per Ton (Rp) CAPEX / OPEX  \
0                  Operasi Produksi  ...            1112412         OPEX
1                        Eksplorasi  ...             902738        CAPEX
2                        Eksplorasi  ...             968626        CAPEX
3                  Operasi Produksi  ...            1141389        CAPEX
4                  Operasi Produksi  ...             903190         OPEX

  TRIFR LTIFR  Jumlah Insiden  Indikator Fatalitas  \
0  2.21  0.36               1                Tidak
1  1.58  0.38               1                Tidak
2  0.51  0.29               2                Tidak
3  1.80  0.43               1                Tidak
4  2.15  0.15               0                Tidak

   Harga Nikel Historis (Rp/Ton) Nilai Tukar (Rp/USD) Pembeli / Offtaker  \
0                      263562245                15911            PT IWIP
1                      344250926                15541             PT GNI
2                      297510835                15583   PT Aneka Tambang
3                      281917397                15809            PT IMIP
4                      294606097                16044            PT IMIP

   Jenis Kontrak
0  FOB Motorship
1            CIF
2            CIF
3  FOB Motorship
4  Spot Contract

[5 rows x 49 columns]
               Name          Province UNLCODE  Latitude  Longitude  \
0            JAMPEA  SULAWESI SELATAN       -   -7.0581   120.6100
1           BENTENG  SULAWESI SELATAN       -   -6.1166   120.4512
2     MAKASSAR ANCH  SULAWESI SELATAN       -   -5.1195   119.3628
3          MAKASSAR  SULAWESI SELATAN   IDMAK   -5.1236   119.4177
4  BIRINGKASSI ANCH  SULAWESI SELATAN       -   -4.8226   119.4630

   VesselInPort  ExpectedArrival  RecentPortCalls       Type
0             0                0                0      PORT
1             0                0                0       PORT
2            17                0               22  ANCHORAGE
3            29               13               29       PORT
4             9                0                3  ANCHORAGE

In [20]:
# Check shape
print("Mines shape:", mines.shape)
print("Ports shape:", ports.shape)

Mines shape: (264, 49)
Ports shape: (74, 9)

In [38]:
# Check mines column
mines.columns.tolist()

['Kecamatan',
 'Kabupaten',
 'Nama objek',
 'Nomor Lokasi Keterdapatan',
 'Komoditi',
 'Kode Unsur',
 'Kelompok Mineral Logam',
 'Lokasi Keterdapatan',
 'Provinsi',
 'Status Penyelidikan Mineral Logam',
 'Bijih Terbukti (Ton)',
 'Logam Terbukti (Ton)',
 'keterangan',
 'acuan',
 'objectid',
 'longitude',
 'latitude',
 'Jenis Izin',
 'Lokasi Tambang',
 'Luas Wilayah',
 'Tanggal Berakhir SK',
 'Tanggal Berlaku SK',
 'Mine_port(meter)',
 'Mine_road(meter)',
 'Mine_Smelter(meter)',
 'Produksi Tahunan (ton)',
 'Target Produksi Harian (ton)',
 'Produksi Aktual Harian (ton)',
 'Pencapaian (%)',
 'Jumlah Ekskavator',
 'Jumlah Truk Tambang',
 'Ketersediaan Fisik (PA) %',
 'Penggunaan Ketersediaan (UA) %',
 'Jam Downtime',
 'Konsumsi BBM (Liter)',
 'Biaya Penambangan per Ton (Rp)',
 'Biaya Pengangkutan per Ton (Rp)',
 'Biaya Penanganan Pelabuhan per Ton (Rp)',
 'Biaya Pemrosesan Smelter per Ton (Rp)',
 'AISC per Ton (Rp)',
 'CAPEX / OPEX',
 'TRIFR',
 'LTIFR',
 'Jumlah Insiden',
 'Indikator Fatalitas',
 'Harga Nikel Historis (Rp/Ton)',
 'Nilai Tukar (Rp/USD)',
 'Pembeli / Offtaker',
 'Jenis Kontrak']

In [37]:
# Check ports column
ports.columns.tolist()

['Name',
 'Province',
 'UNLCODE',
 'Latitude',
 'Longitude',
 'VesselInPort',
 'ExpectedArrival',
 'RecentPortCalls',
 'Type']

In [23]:
# Check mines type
mines.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264 entries, 0 to 263
Data columns (total 49 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Kecamatan                                264 non-null    object
 1   Kabupaten                                264 non-null    object
 2   Nama objek                               264 non-null    object
 3   Nomor Lokasi Keterdapatan                264 non-null    object
 4   Komoditi                                 264 non-null    object
 5   Kode Unsur                               264 non-null    object
 6   Kelompok Mineral Logam                   264 non-null    object
 7   Lokasi Keterdapatan                      264 non-null    object
 8   Provinsi                                 264 non-null    object
 9   Status Penyelidikan Mineral Logam        264 non-null    object
 10  Bijih Terbukti (Ton)                     264 non-null    float64
 11  Logam Terbukti (Ton)                     264 non-null    object
 12  keteragan                                264 non-null    object
 13  acuan                                    264 non-null    object
 14  objectid                                 264 non-null    int64
 15  longitude                                264 non-null    float64
 16  latitude                                 264 non-null    float64
 17  Jenis Izin                               264 non-null    object
 18  Lokasi Tambang                           264 non-null    object
 19  Luas Wilayah                             264 non-null    object
 20  Tanggal Berakhir SK                      264 non-null    object
 21  Tanggal Berlaku SK                       264 non-null    object
 22  Mine_port(meter)                         235 non-null    float64
 23  Mine_road(meter)                         235 non-null    float64
 24  Mine_Smelter(meter)                      235 non-null    float64
 25  Produksi Tahunan (ton)                   264 non-null    int64
 26  Target Produksi Harian (ton)             264 non-null    int64
 27  Produksi Aktual Harian (ton)             264 non-null    int64
 28  Pencapaian (%)                           264 non-null    float64
 29  Jumlah Ekskavator                        264 non-null    int64
 30  Jumlah Truk Tambang                      264 non-null    int64
 31  Ketersediaan Fisik (PA) %                264 non-null    float64
 32  Penggunaan Ketersediaan (UA) %           264 non-null    float64
 33  Jam Downtime                             264 non-null    float64
 34  Konsumsi BBM (Liter)                     264 non-null    int64
 35  Biaya Penambangan per Ton (Rp)           264 non-null    int64
 36  Biaya Pengangkutan per Ton (Rp)          264 non-null    int64
 37  Biaya Penanganan Pelabuhan per Ton (Rp)  264 non-null    int64
 38  Biaya Pemrosesan Smelter per Ton (Rp)    264 non-null    int64
 39  AISC per Ton (Rp)                        264 non-null    int64
 40  CAPEX / OPEX                             264 non-null    object
 41  TRIFR                                    264 non-null    float64
 42  LTIFR                                    264 non-null    float64
 43  Jumlah Insiden                           264 non-null    int64
 44  Indikator Fatalitas                      264 non-null    object
 45  Harga Nikel Historis (Rp/Ton)            264 non-null    int64
 46  Nilai Tukar (Rp/USD)                     264 non-null    int64
 47  Pembeli / Offtaker                       264 non-null    object
 48  Jenis Kontrak                            264 non-null    object
dtypes: float64(12), int64(15), object(22)
memory usage: 101.2+ KB

In [24]:
# Check ports type
ports.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             74 non-null     object
 1   Province         74 non-null     object
 2   UNLCODE          74 non-null     object
 3   Latitude         74 non-null     float64
 4   Longitude        74 non-null     float64
 5   VesselInPort     74 non-null     int64
 6   ExpectedArrival  74 non-null     int64
 7   RecentPortCalls  74 non-null     int64
 8   Type             74 non-null     object
dtypes: float64(2), int64(3), object(4)
memory usage: 5.3+ KB

In [25]:
# Check mines describe
mines.describe(include="all")

,Kecamatan,Kabupaten,Nama objek,Nomor Lokasi Keterdapatan,Komoditi,Kode Unsur,Kelompok Mineral Logam,Lokasi Keterdapatan,Provinsi,Status Penyelidikan Mineral Logam,...,AISC per Ton (Rp),CAPEX / OPEX,TRIFR,LTIFR,Jumlah Insiden,Indikator Fatalitas,Harga Nikel Historis (Rp/Ton),Nilai Tukar (Rp/USD),Pembeli / Offtaker,Jenis Kontrak
count,264,264,264,264,264,264,264,264,264,264,...,2.640000e+02,264,264.000000,264.000000,264.000000,264,2.640000e+02,264.000000,264,264
unique,72,20,262,264,1,1,1,262,5,5,...,NaN,2,NaN,NaN,NaN,2,NaN,NaN,5,3
top,Molawe,Konawe Utara,Nikel Tambea,1.438.000.000,Nikel,Ni,Logam Besi dan Paduan Besi,Tambea,Sulawesi Tenggara,Operasi Produksi,...,NaN,CAPEX,NaN,NaN,NaN,Tidak,NaN,NaN,PT Vale Indonesia,Spot Contract
freq,34,66,2,1,264,264,264,2,149,232,...,NaN,140,NaN,NaN,NaN,258,NaN,NaN,76,90
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.049082e+06,NaN,1.370492,0.252197,0.969697,NaN,2.992076e+08,15784.102273,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.332054e+05,NaN,0.662255,0.143888,0.831320,NaN,2.880716e+07,157.476514,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.403820e+05,NaN,0.210000,0.000000,0.000000,NaN,2.502387e+08,15500.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.368082e+05,NaN,0.767500,0.120000,0.000000,NaN,2.750758e+08,15661.000000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.048340e+06,NaN,1.440000,0.250000,1.000000,NaN,3.001124e+08,15786.500000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.146986e+06,NaN,1.930000,0.372500,2.000000,NaN,3.227872e+08,15917.250000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.368381e+06,NaN,2.490000,0.500000,2.000000,NaN,3.499409e+08,16048.000000,NaN,NaN

In [26]:
# Check ports describe
ports.describe(include="all")

,Name,Province,UNLCODE,Latitude,Longitude,VesselInPort,ExpectedArrival,RecentPortCalls,Type
count,74,74,74,74.000000,74.000000,74.000000,74.000000,74.00000,74
unique,74,7,40,NaN,NaN,NaN,NaN,NaN,4
top,JAMPEA,MALUKU,-,NaN,NaN,NaN,NaN,NaN,PORT
freq,1,18,35,NaN,NaN,NaN,NaN,NaN,57
mean,NaN,NaN,NaN,-2.411132,124.629134,3.148649,2.000000,4.27027,NaN
std,NaN,NaN,NaN,2.700935,3.944202,7.289855,6.333213,10.06186,NaN
min,NaN,NaN,NaN,-8.079400,119.362800,0.000000,0.000000,0.00000,NaN
25%,NaN,NaN,NaN,-4.314100,121.071725,0.000000,0.000000,0.00000,NaN
50%,NaN,NaN,NaN,-2.857850,123.714950,0.000000,0.000000,0.00000,NaN
75%,NaN,NaN,NaN,-0.282675,127.661000,2.000000,1.000000,2.00000,NaN
max,NaN,NaN,NaN,4.000000,134.211500,40.000000,50.000000,55.00000,NaN

In [27]:
# Check missing data
mines.isnull().sum()

Kecamatan                                   0
Kabupaten                                   0
Nama objek                                  0
Nomor Lokasi Keterdapatan                   0
Komoditi                                    0
Kode Unsur                                  0
Kelompok Mineral Logam                      0
Lokasi Keterdapatan                         0
Provinsi                                    0
Status Penyelidikan Mineral Logam           0
Bijih Terbukti (Ton)                        0
Logam Terbukti (Ton)                        0
keteragan                                   0
acuan                                       0
objectid                                    0
longitude                                   0
latitude                                    0
Jenis Izin                                  0
Lokasi Tambang                              0
Luas Wilayah                                0
Tanggal Berakhir SK                         0
Tanggal Berlaku SK                          0
Mine_port(meter)                           29
Mine_road(meter)                           29
Mine_Smelter(meter)                        29
Produksi Tahunan (ton)                      0
Target Produksi Harian (ton)                0
Produksi Aktual Harian (ton)                0
Pencapaian (%)                              0
Jumlah Ekskavator                           0
Jumlah Truk Tambang                         0
Ketersediaan Fisik (PA) %                   0
Penggunaan Ketersediaan (UA) %              0
Jam Downtime                                0
Konsumsi BBM (Liter)                        0
Biaya Penambangan per Ton (Rp)              0
Biaya Pengangkutan per Ton (Rp)             0
Biaya Penanganan Pelabuhan per Ton (Rp)     0
Biaya Pemrosesan Smelter per Ton (Rp)       0
AISC per Ton (Rp)                           0
CAPEX / OPEX                                0
TRIFR                                       0
LTIFR                                       0
Jumlah Insiden                              0
Indikator Fatalitas                         0
Harga Nikel Historis (Rp/Ton)               0
Nilai Tukar (Rp/USD)                        0
Pembeli / Offtaker                          0
Jenis Kontrak                               0
dtype: int64

In [28]:
ports.isnull().sum()

Name               0
Province           0
UNLCODE            0
Latitude           0
Longitude          0
VesselInPort       0
ExpectedArrival    0
RecentPortCalls    0
Type               0
dtype: int64

In [29]:
# Check duplicate data
mines.duplicated().sum()

np.int64(0)

In [30]:
ports.duplicated().sum()

np.int64(0)

DATA CLEANING

In [31]:
# Clean the column
mines.columns = mines.columns.str.strip()
ports.columns = ports.columns.str.strip()

In [33]:
# Clean typo
mines.rename(
    columns={
        "keteragan": "keterangan"
    },
    inplace=True
)

In [32]:
# Cleaning big numeric columns
big_number_cols = [
    "Nomor Lokasi Keterdapatan",
    "Bijih Terbukti (Ton)",
    "Logam Terbukti (Ton)"
]

for col in big_number_cols:
    mines[col] = (
        mines[col]
        .astype(str)
        .str.replace(".", "", regex=False)
        .str.replace(",", ".", regex=False)
    )

    mines[col] = pd.to_numeric(
        mines[col],
        errors="coerce"
    )

In [34]:
# Cleaning coordinate columns
coord_cols = [
    "longitude",
    "latitude"
]

for col in coord_cols:
    mines[col] = pd.to_numeric(
        mines[col],
        errors="coerce"
    )

In [35]:
# Clean port numeric columns
port_num_cols = [
    "Latitude",
    "Longitude",
    "VesselInPort",
    "ExpectedArrival",
    "RecentPortCalls"
]

for col in port_num_cols:
    ports[col] = pd.to_numeric(
        ports[col],
        errors="coerce"
    )

In [39]:
# Cleaning distance columns
distance_cols = [
    "Mine_port(meter)",
    "Mine_road(meter)",
    "Mine_Smelter(meter)",
    "Luas Wilayah"
]

for col in distance_cols:
    mines[col] = (
        mines[col]
        .astype(str)
        .str.replace(".", "", regex=False)
        .str.replace(",", ".", regex=False)
    )

    mines[col] = pd.to_numeric(
        mines[col],
        errors="coerce"
    )

In [40]:
# Create month dictionary
bulan_map = {
    "Januari": "January",
    "Februari": "February",
    "Maret": "March",
    "April": "April",
    "Mei": "May",
    "Juni": "June",
    "Juli": "July",
    "Agustus": "August",
    "September": "September",
    "Oktober": "October",
    "November": "November",
    "Desember": "December"
}

In [41]:
# Replace Indonesian month names
date_cols = [
    "Tanggal Berakhir SK",
    "Tanggal Berlaku SK"
]

for col in date_cols:
    for indo, eng in bulan_map.items():
        mines[col] = mines[col].str.replace(
            indo,
            eng,
            regex=False
        )

In [42]:
# Convert to datetime
for col in date_cols:
    mines[col] = pd.to_datetime(
        mines[col],
        errors="coerce"
    )

In [43]:
mines[[
    "Tanggal Berakhir SK",
    "Tanggal Berlaku SK"
]].isnull().sum()

Tanggal Berakhir SK    2
Tanggal Berlaku SK     2
dtype: int64

In [44]:
mines[mines["Luas Wilayah"].isnull()]

,Kecamatan,Kabupaten,Nama objek,Nomor Lokasi Keterdapatan,Komoditi,Kode Unsur,Kelompok Mineral Logam,Lokasi Keterdapatan,Provinsi,Status Penyelidikan Mineral Logam,...,AISC per Ton (Rp),CAPEX / OPEX,TRIFR,LTIFR,Jumlah Insiden,Indikator Fatalitas,Harga Nikel Historis (Rp/Ton),Nilai Tukar (Rp/USD),Pembeli / Offtaker,Jenis Kontrak
249,Wasile,Halmahera Timur,Nikel Fayaul,1425000000,Nikel,Ni,Logam Besi dan Paduan Besi,Fayaul,Maluku Utara,Operasi Produksi,...,844655,CAPEX,1.17,0.06,1,Tidak,317756315,15842,PT Aneka Tambang,FOB Motorship
250,Wasile,Halmahera Timur,Nikel Saramaake,1426000000,Nikel,Ni,Logam Besi dan Paduan Besi,Saramaake,Maluku Utara,Explorasi,...,1073201,CAPEX,1.49,0.07,1,Tidak,258635967,15735,PT Vale Indonesia,FOB Motorship

In [45]:
# Check data
print(mines.head())
print(ports.head())

   Kecamatan   Kabupaten                            Nama objek  \
0     Malili  Luwu Timur  Nikel Desa Harapan dan Desa Pongkeru
1     Towuti  Luwu Timur               Nikel Limonite Sorowako
2  Wasuponda  Luwu Timur              Nikel Soroako-Petea HPAL
3     Malili  Luwu Timur                            Nikel Ussu
4     Malili  Luwu Timur  Nikel Blok Pongkeru dan Blok Harapan

   Nomor Lokasi Keterdapatan Komoditi Kode Unsur      Kelompok Mineral Logam  \
0                  283000000    Nikel         Ni  Logam Besi dan Paduan Besi
1                  281000000    Nikel         Ni  Logam Besi dan Paduan Besi
2                 1921000000    Nikel         Ni  Logam Besi dan Paduan Besi
3                 2136000000    Nikel         Ni  Logam Besi dan Paduan Besi
4                 2816000000    Nikel         Ni  Logam Besi dan Paduan Besi

              Lokasi Keterdapatan          Provinsi  \
0  Desa Harapan dan Desa Pongkeru  Sulawesi Selatan
1               Limonite Sorowako  Sulawesi Selatan
2              Soroako-Petea HPAL  Sulawesi Selatan
3                            Ussu  Sulawesi Selatan
4  Blok Pongkeru dan Blok Harapan  Sulawesi Selatan

  Status Penyelidikan Mineral Logam  ...  AISC per Ton (Rp)  CAPEX / OPEX  \
0                  Operasi Produksi  ...            1112412          OPEX
1                        Eksplorasi  ...             902738         CAPEX
2                        Eksplorasi  ...             968626         CAPEX
3                  Operasi Produksi  ...            1141389         CAPEX
4                  Operasi Produksi  ...             903190          OPEX

  TRIFR LTIFR  Jumlah Insiden  Indikator Fatalitas  \
0  2.21  0.36               1                Tidak
1  1.58  0.38               1                Tidak
2  0.51  0.29               2                Tidak
3  1.80  0.43               1                Tidak
4  2.15  0.15               0                Tidak

   Harga Nikel Historis (Rp/Ton) Nilai Tukar (Rp/USD) Pembeli / Offtaker  \
0                      263562245                15911            PT IWIP
1                      344250926                15541             PT GNI
2                      297510835                15583   PT Aneka Tambang
3                      281917397                15809            PT IMIP
4                      294606097                16044            PT IMIP

   Jenis Kontrak
0  FOB Motorship
1            CIF
2            CIF
3  FOB Motorship
4  Spot Contract

[5 rows x 49 columns]
               Name          Province UNLCODE  Latitude  Longitude  \
0            JAMPEA  SULAWESI SELATAN       -   -7.0581   120.6100
1           BENTENG  SULAWESI SELATAN       -   -6.1166   120.4512
2     MAKASSAR ANCH  SULAWESI SELATAN       -   -5.1195   119.3628
3          MAKASSAR  SULAWESI SELATAN   IDMAK   -5.1236   119.4177
4  BIRINGKASSI ANCH  SULAWESI SELATAN       -   -4.8226   119.4630

   VesselInPort  ExpectedArrival  RecentPortCalls       Type
0             0                0                0      PORT
1             0                0                0       PORT
2            17                0               22  ANCHORAGE
3            29               13               29       PORT
4             9                0                3  ANCHORAGE

DATA VALIDATION

In [46]:
mines.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264 entries, 0 to 263
Data columns (total 49 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Kecamatan                                264 non-null    object
 1   Kabupaten                                264 non-null    object
 2   Nama objek                               264 non-null    object
 3   Nomor Lokasi Keterdapatan                264 non-null    int64
 4   Komoditi                                 264 non-null    object
 5   Kode Unsur                               264 non-null    object
 6   Kelompok Mineral Logam                   264 non-null    object
 7   Lokasi Keterdapatan                      264 non-null    object
 8   Provinsi                                 264 non-null    object
 9   Status Penyelidikan Mineral Logam        264 non-null    object
 10  Bijih Terbukti (Ton)                     264 non-null    int64
 11  Logam Terbukti (Ton)                     264 non-null    int64
 12  keterangan                               264 non-null    object
 13  acuan                                    264 non-null    object
 14  objectid                                 264 non-null    int64
 15  longitude                                264 non-null    float64
 16  latitude                                 264 non-null    float64
 17  Jenis Izin                               264 non-null    object
 18  Lokasi Tambang                           264 non-null    object
 19  Luas Wilayah                             262 non-null    float64
 20  Tanggal Berakhir SK                      262 non-null    datetime64[ns]
 21  Tanggal Berlaku SK                       262 non-null    datetime64[ns]
 22  Mine_port(meter)                         235 non-null    float64
 23  Mine_road(meter)                         235 non-null    float64
 24  Mine_Smelter(meter)                      235 non-null    float64
 25  Produksi Tahunan (ton)                   264 non-null    int64
 26  Target Produksi Harian (ton)             264 non-null    int64
 27  Produksi Aktual Harian (ton)             264 non-null    int64
 28  Pencapaian (%)                           264 non-null    float64
 29  Jumlah Ekskavator                        264 non-null    int64
 30  Jumlah Truk Tambang                      264 non-null    int64
 31  Ketersediaan Fisik (PA) %                264 non-null    float64
 32  Penggunaan Ketersediaan (UA) %           264 non-null    float64
 33  Jam Downtime                             264 non-null    float64
 34  Konsumsi BBM (Liter)                     264 non-null    int64
 35  Biaya Penambangan per Ton (Rp)           264 non-null    int64
 36  Biaya Pengangkutan per Ton (Rp)          264 non-null    int64
 37  Biaya Penanganan Pelabuhan per Ton (Rp)  264 non-null    int64
 38  Biaya Pemrosesan Smelter per Ton (Rp)    264 non-null    int64
 39  AISC per Ton (Rp)                        264 non-null    int64
 40  CAPEX / OPEX                             264 non-null    object
 41  TRIFR                                    264 non-null    float64
 42  LTIFR                                    264 non-null    float64
 43  Jumlah Insiden                           264 non-null    int64
 44  Indikator Fatalitas                      264 non-null    object
 45  Harga Nikel Historis (Rp/Ton)            264 non-null    int64
 46  Nilai Tukar (Rp/USD)                     264 non-null    int64
 47  Pembeli / Offtaker                       264 non-null    object
 48  Jenis Kontrak                            264 non-null    object
dtypes: datetime64[ns](2), float64(12), int64(18), object(17)
memory usage: 101.2+ KB

In [47]:
mines.describe()

,Nomor Lokasi Keterdapatan,Bijih Terbukti (Ton),Logam Terbukti (Ton),objectid,longitude,latitude,Luas Wilayah,Tanggal Berakhir SK,Tanggal Berlaku SK,Mine_port(meter),...,Biaya Penambangan per Ton (Rp),Biaya Pengangkutan per Ton (Rp),Biaya Penanganan Pelabuhan per Ton (Rp),Biaya Pemrosesan Smelter per Ton (Rp),AISC per Ton (Rp),TRIFR,LTIFR,Jumlah Insiden,Harga Nikel Historis (Rp/Ton),Nilai Tukar (Rp/USD)
count,2.640000e+02,2.640000e+02,2.640000e+02,264.000000,264.000000,264.000000,262.000000,262,262,2.350000e+02,...,264.000000,264.000000,264.000000,264.000000,2.640000e+02,264.000000,264.000000,264.000000,2.640000e+02,264.000000
mean,1.975182e+09,5.403553e+07,9.614298e+09,1501.420455,122.993081,-2.746815,52578.099237,2031-05-27 20:25:38.931297792,2015-10-04 06:30:13.740457984,2.985920e+07,...,299955.848485,100077.731061,53758.113636,595290.522727,1.049082e+06,1.370492,0.252197,0.969697,2.992076e+08,15784.102273
min,2.710000e+08,0.000000e+00,0.000000e+00,1291.000000,120.915200,-5.436000,1000.000000,1930-04-22 00:00:00,2007-07-12 00:00:00,5.553200e+04,...,200113.000000,50882.000000,30157.000000,403033.000000,7.403820e+05,0.210000,0.000000,0.000000,2.502387e+08,15500.000000
25%,1.414750e+09,0.000000e+00,0.000000e+00,1423.750000,121.701000,-3.826050,3895.250000,2029-12-22 00:00:00,2011-10-27 00:00:00,1.071671e+07,...,249237.250000,73022.250000,42399.500000,504215.000000,9.368082e+05,0.767500,0.120000,0.000000,2.750758e+08,15661.000000
50%,2.162500e+09,5.725800e+06,3.958500e+04,1511.500000,122.226850,-3.213050,12665.000000,2031-07-11 12:00:00,2015-04-21 00:00:00,2.441279e+07,...,298911.000000,101864.000000,52680.500000,583590.000000,1.048340e+06,1.440000,0.250000,1.000000,3.001124e+08,15786.500000
75%,2.566500e+09,3.480630e+07,7.097665e+07,1588.500000,122.372450,-1.973750,40092.500000,2032-10-19 00:00:00,2019-08-28 00:00:00,4.818215e+07,...,348901.750000,123387.750000,65747.750000,704236.250000,1.146986e+06,1.930000,0.372500,2.000000,3.227872e+08,15917.250000
max,2.946000e+09,2.694000e+09,4.561060e+11,1666.000000,129.551000,1.597500,705660.000000,2048-02-27 00:00:00,2024-11-19 00:00:00,9.705675e+07,...,399736.000000,149882.000000,79640.000000,799906.000000,1.368381e+06,2.490000,0.500000,2.000000,3.499409e+08,16048.000000
std,7.960999e+08,2.170938e+08,4.717177e+10,104.607111,2.350677,1.651339,119252.962381,NaN,NaN,2.206601e+07,...,57287.801099,29132.955499,14275.243381,116160.707747,1.332054e+05,0.662255,0.143888,0.831320,2.880716e+07,157.476514

In [49]:
mines.head()

,Kecamatan,Kabupaten,Nama objek,Nomor Lokasi Keterdapatan,Komoditi,Kode Unsur,Kelompok Mineral Logam,Lokasi Keterdapatan,Provinsi,Status Penyelidikan Mineral Logam,...,AISC per Ton (Rp),CAPEX / OPEX,TRIFR,LTIFR,Jumlah Insiden,Indikator Fatalitas,Harga Nikel Historis (Rp/Ton),Nilai Tukar (Rp/USD),Pembeli / Offtaker,Jenis Kontrak
0,Malili,Luwu Timur,Nikel Desa Harapan dan Desa Pongkeru,283000000,Nikel,Ni,Logam Besi dan Paduan Besi,Desa Harapan dan Desa Pongkeru,Sulawesi Selatan,Operasi Produksi,...,1112412,OPEX,2.21,0.36,1,Tidak,263562245,15911,PT IWIP,FOB Motorship
1,Towuti,Luwu Timur,Nikel Limonite Sorowako,281000000,Nikel,Ni,Logam Besi dan Paduan Besi,Limonite Sorowako,Sulawesi Selatan,Eksplorasi,...,902738,CAPEX,1.58,0.38,1,Tidak,344250926,15541,PT GNI,CIF
2,Wasuponda,Luwu Timur,Nikel Soroako-Petea HPAL,1921000000,Nikel,Ni,Logam Besi dan Paduan Besi,Soroako-Petea HPAL,Sulawesi Selatan,Eksplorasi,...,968626,CAPEX,0.51,0.29,2,Tidak,297510835,15583,PT Aneka Tambang,CIF
3,Malili,Luwu Timur,Nikel Ussu,2136000000,Nikel,Ni,Logam Besi dan Paduan Besi,Ussu,Sulawesi Selatan,Operasi Produksi,...,1141389,CAPEX,1.80,0.43,1,Tidak,281917397,15809,PT IMIP,FOB Motorship
4,Malili,Luwu Timur,Nikel Blok Pongkeru dan Blok Harapan,2816000000,Nikel,Ni,Logam Besi dan Paduan Besi,Blok Pongkeru dan Blok Harapan,Sulawesi Selatan,Operasi Produksi,...,903190,OPEX,2.15,0.15,0,Tidak,294606097,16044,PT IMIP,Spot Contract

In [50]:
mines[["latitude", "longitude"]].describe()

         latitude   longitude
count  264.000000  264.000000
mean    -2.746815  122.993081
std      1.651339    2.350677
min     -5.436000  120.915200
25%     -3.826050  121.701000
50%     -3.213050  122.226850
75%     -1.973750  122.372450
max      1.597500  129.551000

In [51]:
ports.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             74 non-null     object
 1   Province         74 non-null     object
 2   UNLCODE          74 non-null     object
 3   Latitude         74 non-null     float64
 4   Longitude        74 non-null     float64
 5   VesselInPort     74 non-null     int64
 6   ExpectedArrival  74 non-null     int64
 7   RecentPortCalls  74 non-null     int64
 8   Type             74 non-null     object
dtypes: float64(2), int64(3), object(4)
memory usage: 5.3+ KB

In [52]:
ports.describe()

        Latitude   Longitude  VesselInPort  ExpectedArrival  RecentPortCalls
count  74.000000   74.000000     74.000000        74.000000         74.00000
mean   -2.411132  124.629134      3.148649         2.000000          4.27027
std     2.700935    3.944202      7.289855         6.333213         10.06186
min    -8.079400  119.362800      0.000000         0.000000          0.00000
25%    -4.314100  121.071725      0.000000         0.000000          0.00000
50%    -2.857850  123.714950      0.000000         0.000000          0.00000
75%    -0.282675  127.661000      2.000000         1.000000          2.00000
max     4.000000  134.211500     40.000000        50.000000         55.00000

In [53]:
mines[mines["Luas Wilayah"].isnull()]

,Kecamatan,Kabupaten,Nama objek,Nomor Lokasi Keterdapatan,Komoditi,Kode Unsur,Kelompok Mineral Logam,Lokasi Keterdapatan,Provinsi,Status Penyelidikan Mineral Logam,...,AISC per Ton (Rp),CAPEX / OPEX,TRIFR,LTIFR,Jumlah Insiden,Indikator Fatalitas,Harga Nikel Historis (Rp/Ton),Nilai Tukar (Rp/USD),Pembeli / Offtaker,Jenis Kontrak
249,Wasile,Halmahera Timur,Nikel Fayaul,1425000000,Nikel,Ni,Logam Besi dan Paduan Besi,Fayaul,Maluku Utara,Operasi Produksi,...,844655,CAPEX,1.17,0.06,1,Tidak,317756315,15842,PT Aneka Tambang,FOB Motorship
250,Wasile,Halmahera Timur,Nikel Saramaake,1426000000,Nikel,Ni,Logam Besi dan Paduan Besi,Saramaake,Maluku Utara,Explorasi,...,1073201,CAPEX,1.49,0.07,1,Tidak,258635967,15735,PT Vale Indonesia,FOB Motorship

FEATURE ENGINEERING

In [54]:
# Add mining permit age
mines["License_Duration_Years"] = (
    mines["Tanggal Berakhir SK"] -
    mines["Tanggal Berlaku SK"]
).dt.days / 365

In [55]:
# Add active permission status
today = pd.Timestamp.today()

mines["License_Status"] = np.where(
    mines["Tanggal Berakhir SK"] > today,
    "Active",
    "Expired"
)

SAVE DATA

In [163]:
# Save mines data
mines.to_csv(
    f"{BASE_PATH}/cleaned_mines_final.csv",
    index=False
)

In [164]:
# Save port data
ports.to_csv(
    f"{BASE_PATH}/cleaned_ports.csv",
    index=False
)