In [1]:
!pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 76.3 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12

In [34]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [82]:
# Import Library
import pandas as pd
import numpy as np
import os

In [83]:
# Load dataset
BASE_PATH = "/content/drive/MyDrive/Nickel Mining and Smelter in Sulawesi-Maluku"

In [84]:
# Check folder
os.listdir(BASE_PATH)

['Dataset Hilirisasi - Tambang Nikel Sul-Mal Final.csv',
 'Dataset pelabuhan - Maluku.csv',
 'Dataset pelabuhan - Sulawesi.csv']

In [85]:
# Load mines data
mines = pd.read_csv(
    f"{BASE_PATH}/Dataset Hilirisasi - Tambang Nikel Sul-Mal Final.csv"
)

mines.head()

,Kecamatan,Kabupaten,Nama objek,Nomor Lokasi Keterdapatan,Komoditi,Kode Unsur,Kelompok Mineral Logam,Lokasi Keterdapatan,Provinsi,Status Penyelidikan Mineral Logam,...,longitude,latitude,Jenis Izin,Lokasi Tambang,Luas Wilayah,Tanggal Berakhir SK,Tanggal Berlaku SK,Mine_port(meter),Mine_road(meter),Mine_Smelter(meter)
0,Malili,Luwu Timur,Nikel Desa Harapan dan Desa Pongkeru,283.000.000,Nikel,Ni,Logam Besi dan Paduan Besi,Desa Harapan dan Desa Pongkeru,Sulawesi Selatan,Operasi Produksi,...,121.153,-2.7880,IUP,Desa Harapan Kec Malili Kab Luwu Timur,2660,"November 3, 2029","Juli 6, 2018",10999.274,427.609,34735.389
1,Towuti,Luwu Timur,Nikel Limonite Sorowako,281.000.000,Nikel,Ni,Logam Besi dan Paduan Besi,Limonite Sorowako,Sulawesi Selatan,Eksplorasi,...,121.386,-2.6170,IUPK,Blok Soroako. Kab. Luwu timur dan Kab. Morowali,70566,"Desember 28, 2035","Mei 3, 2024",NaN,NaN,NaN
2,Wasuponda,Luwu Timur,Nikel Soroako-Petea HPAL,1.921.000.000,Nikel,Ni,Logam Besi dan Paduan Besi,Soroako-Petea HPAL,Sulawesi Selatan,Eksplorasi,...,121.242,-2.6420,IUPK,Blok Soroako. Kab. Luwu timur dan Kab. Morowali,70566,"Desember 28, 2035","Mei 3, 2024",NaN,NaN,NaN
3,Malili,Luwu Timur,Nikel Ussu,2.136.000.000,Nikel,Ni,Logam Besi dan Paduan Besi,Ussu,Sulawesi Selatan,Operasi Produksi,...,121.075,-2.5710,IUP,"Desa Ussu, Kec. Malili, Kab.Luwu Timur",1419,"April 18, 2031","April 18, 2011",7801.659,1707.929,33707.756
4,Malili,Luwu Timur,Nikel Blok Pongkeru dan Blok Harapan,2.816.000.000,Nikel,Ni,Logam Besi dan Paduan Besi,Blok Pongkeru dan Blok Harapan,Sulawesi Selatan,Operasi Produksi,...,121.153,-2.7885,IUP,Desa Harapan dan Pongkeru. Kec malili,303,"September 17, 2031","September 10, 2021",11026.502,449.858,34773.727

In [86]:
# Load Sulawesi port
ports_sul = pd.read_csv(
    f"{BASE_PATH}/Dataset pelabuhan - Sulawesi.csv",
    sep=";"
)

ports_sul.head()

,Name,Province,UNLCODE,Latitude,Longitude,VesselInPort,ExpectedArrival,RecentPortCalls,Type
0,JAMPEA,SULAWESI SELATAN,-,-7.0581,120.6100,0,0,0,PORT
1,BENTENG,SULAWESI SELATAN,-,-6.1166,120.4512,0,0,0,PORT
2,MAKASSAR ANCH,SULAWESI SELATAN,-,-5.1195,119.3628,17,0,22,ANCHORAGE
3,MAKASSAR,SULAWESI SELATAN,IDMAK,-5.1236,119.4177,29,13,29,PORT
4,BIRINGKASSI ANCH,SULAWESI SELATAN,-,-4.8226,119.4630,9,0,3,ANCHORAGE

In [87]:
# Load Maluku port
ports_mal = pd.read_csv(
    f"{BASE_PATH}/Dataset pelabuhan - Maluku.csv",
    sep=";"
)

ports_mal.head()

,Name,Province,UNLCODE,Latitude,Longitude,VesselInPort,ExpectedArrival,RecentPortCalls,Type
0,KISAR,MALUKU,-,-8.0794,127.1479,0,0,0,PORT
1,LETI,MALUKU,-,-0.1685,127.6626,0,0,0,PORT
2,SAUMLAKI,MALUKU,IDSXK,-7.9829,131.2947,2,1,3,PORT
3,SAUMLAKI ANCH,MALUKU,-,-7.9875,131.2734,1,0,2,ANCHORAGE
4,DOBO,MALUKU,IDDOB,-5.7524,134.2115,0,0,0,PORT

In [88]:
# Merge ports
ports = pd.concat(
    [ports_sul, ports_mal],
    ignore_index=True
)

ports.head()

,Name,Province,UNLCODE,Latitude,Longitude,VesselInPort,ExpectedArrival,RecentPortCalls,Type
0,JAMPEA,SULAWESI SELATAN,-,-7.0581,120.6100,0,0,0,PORT
1,BENTENG,SULAWESI SELATAN,-,-6.1166,120.4512,0,0,0,PORT
2,MAKASSAR ANCH,SULAWESI SELATAN,-,-5.1195,119.3628,17,0,22,ANCHORAGE
3,MAKASSAR,SULAWESI SELATAN,IDMAK,-5.1236,119.4177,29,13,29,PORT
4,BIRINGKASSI ANCH,SULAWESI SELATAN,-,-4.8226,119.4630,9,0,3,ANCHORAGE

In [89]:
# Check data
print(mines.head())
print(ports.head())

   Kecamatan   Kabupaten                            Nama objek  \
0     Malili  Luwu Timur  Nikel Desa Harapan dan Desa Pongkeru
1     Towuti  Luwu Timur               Nikel Limonite Sorowako
2  Wasuponda  Luwu Timur              Nikel Soroako-Petea HPAL
3     Malili  Luwu Timur                            Nikel Ussu
4     Malili  Luwu Timur  Nikel Blok Pongkeru dan Blok Harapan

  Nomor Lokasi Keterdapatan Komoditi Kode Unsur      Kelompok Mineral Logam  \
0               283.000.000    Nikel         Ni  Logam Besi dan Paduan Besi
1               281.000.000    Nikel         Ni  Logam Besi dan Paduan Besi
2             1.921.000.000    Nikel         Ni  Logam Besi dan Paduan Besi
3             2.136.000.000    Nikel         Ni  Logam Besi dan Paduan Besi
4             2.816.000.000    Nikel         Ni  Logam Besi dan Paduan Besi

              Lokasi Keterdapatan          Provinsi  \
0  Desa Harapan dan Desa Pongkeru  Sulawesi Selatan
1               Limonite Sorowako  Sulawesi Selatan
2              Soroako-Petea HPAL  Sulawesi Selatan
3                            Ussu  Sulawesi Selatan
4  Blok Pongkeru dan Blok Harapan  Sulawesi Selatan

  Status Penyelidikan Mineral Logam  ...  longitude latitude Jenis Izin  \
0                  Operasi Produksi  ...    121.153  -2.7880        IUP
1                        Eksplorasi  ...    121.386  -2.6170       IUPK
2                        Eksplorasi  ...    121.242  -2.6420       IUPK
3                  Operasi Produksi  ...    121.075  -2.5710        IUP
4                  Operasi Produksi  ...    121.153  -2.7885        IUP

                                    Lokasi Tambang  Luas Wilayah  \
0           Desa Harapan Kec Malili Kab Luwu Timur          2660
1  Blok Soroako. Kab. Luwu timur dan Kab. Morowali         70566
2  Blok Soroako. Kab. Luwu timur dan Kab. Morowali         70566
3           Desa Ussu, Kec. Malili, Kab.Luwu Timur          1419
4            Desa Harapan dan Pongkeru. Kec malili           303

   Tanggal Berakhir SK  Tanggal Berlaku SK Mine_port(meter) Mine_road(meter)  \
0     November 3, 2029        Juli 6, 2018        10999.274          427.609
1    Desember 28, 2035         Mei 3, 2024              NaN              NaN
2    Desember 28, 2035         Mei 3, 2024              NaN              NaN
3       April 18, 2031      April 18, 2011         7801.659         1707.929
4   September 17, 2031  September 10, 2021        11026.502          449.858

  Mine_Smelter(meter)
0           34735.389
1                 NaN
2                 NaN
3           33707.756
4           34773.727

[5 rows x 25 columns]
               Name          Province UNLCODE  Latitude  Longitude  \
0            JAMPEA  SULAWESI SELATAN       -   -7.0581   120.6100
1           BENTENG  SULAWESI SELATAN       -   -6.1166   120.4512
2     MAKASSAR ANCH  SULAWESI SELATAN       -   -5.1195   119.3628
3          MAKASSAR  SULAWESI SELATAN   IDMAK   -5.1236   119.4177
4  BIRINGKASSI ANCH  SULAWESI SELATAN       -   -4.8226   119.4630

   VesselInPort  ExpectedArrival  RecentPortCalls       Type
0             0                0                0      PORT
1             0                0                0       PORT
2            17                0               22  ANCHORAGE
3            29               13               29       PORT
4             9                0                3  ANCHORAGE

In [90]:
# Check shape
print("Mines shape:", mines.shape)
print("Ports shape:", ports.shape)

Mines shape: (264, 25)
Ports shape: (74, 9)

In [91]:
# Check mines column
mines.columns.tolist()

['Kecamatan',
 'Kabupaten',
 'Nama objek',
 'Nomor Lokasi Keterdapatan',
 'Komoditi',
 'Kode Unsur',
 'Kelompok Mineral Logam',
 'Lokasi Keterdapatan',
 'Provinsi',
 'Status Penyelidikan Mineral Logam',
 'Bijih Terbukti (Ton)',
 'Logam Terbukti (Ton)',
 'keteragan',
 'acuan',
 'objectid',
 'longitude',
 'latitude',
 'Jenis Izin',
 'Lokasi Tambang',
 'Luas Wilayah',
 'Tanggal Berakhir SK',
 'Tanggal Berlaku SK',
 'Mine_port(meter)',
 'Mine_road(meter)',
 'Mine_Smelter(meter)']

In [92]:
# # Check ports column
ports.columns.tolist()

['Name',
 'Province',
 'UNLCODE',
 'Latitude',
 'Longitude',
 'VesselInPort',
 'ExpectedArrival',
 'RecentPortCalls',
 'Type']

In [93]:
# Check mines type
mines.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264 entries, 0 to 263
Data columns (total 25 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Kecamatan                          264 non-null    object
 1   Kabupaten                          264 non-null    object
 2   Nama objek                         264 non-null    object
 3   Nomor Lokasi Keterdapatan          264 non-null    object
 4   Komoditi                           264 non-null    object
 5   Kode Unsur                         264 non-null    object
 6   Kelompok Mineral Logam             264 non-null    object
 7   Lokasi Keterdapatan                264 non-null    object
 8   Provinsi                           264 non-null    object
 9   Status Penyelidikan Mineral Logam  264 non-null    object
 10  Bijih Terbukti (Ton)               264 non-null    float64
 11  Logam Terbukti (Ton)               264 non-null    object
 12  keteragan                          264 non-null    object
 13  acuan                              264 non-null    object
 14  objectid                           264 non-null    int64
 15  longitude                          264 non-null    float64
 16  latitude                           264 non-null    float64
 17  Jenis Izin                         264 non-null    object
 18  Lokasi Tambang                     264 non-null    object
 19  Luas Wilayah                       264 non-null    object
 20  Tanggal Berakhir SK                264 non-null    object
 21  Tanggal Berlaku SK                 264 non-null    object
 22  Mine_port(meter)                   235 non-null    float64
 23  Mine_road(meter)                   235 non-null    float64
 24  Mine_Smelter(meter)                235 non-null    float64
dtypes: float64(6), int64(1), object(18)
memory usage: 51.7+ KB

In [94]:
# Check ports type
ports.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             74 non-null     object
 1   Province         74 non-null     object
 2   UNLCODE          74 non-null     object
 3   Latitude         74 non-null     float64
 4   Longitude        74 non-null     float64
 5   VesselInPort     74 non-null     int64
 6   ExpectedArrival  74 non-null     int64
 7   RecentPortCalls  74 non-null     int64
 8   Type             74 non-null     object
dtypes: float64(2), int64(3), object(4)
memory usage: 5.3+ KB

In [95]:
# Check mines describe
mines.describe(include="all")

,Kecamatan,Kabupaten,Nama objek,Nomor Lokasi Keterdapatan,Komoditi,Kode Unsur,Kelompok Mineral Logam,Lokasi Keterdapatan,Provinsi,Status Penyelidikan Mineral Logam,...,longitude,latitude,Jenis Izin,Lokasi Tambang,Luas Wilayah,Tanggal Berakhir SK,Tanggal Berlaku SK,Mine_port(meter),Mine_road(meter),Mine_Smelter(meter)
count,264,264,264,264,264,264,264,264,264,264,...,264.000000,264.000000,264,264,264,264,264,235.000000,235.000000,235.000000
unique,72,20,262,264,1,1,1,262,5,5,...,NaN,NaN,3,169,187,172,169,NaN,NaN,NaN
top,Molawe,Konawe Utara,Nikel Tambea,1.438.000.000,Nikel,Ni,Logam Besi dan Paduan Besi,Tambea,Sulawesi Tenggara,Operasi Produksi,...,NaN,NaN,IUP,Kec. Lasolo,301,"Desember 28, 2035","Mei 3, 2024",NaN,NaN,NaN
freq,34,66,2,1,264,264,264,2,149,232,...,NaN,NaN,248,18,9,13,13,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,122.993081,-2.746815,NaN,NaN,NaN,NaN,NaN,31658.286136,1486.749685,33301.765911
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.350677,1.651339,NaN,NaN,NaN,NaN,NaN,21328.000584,1970.884078,38111.731611
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,120.915200,-5.436000,NaN,NaN,NaN,NaN,NaN,2538.236000,1.374000,662.173000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,121.701000,-3.826050,NaN,NaN,NaN,NaN,NaN,11561.917000,231.589500,9756.476500
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,122.226850,-3.213050,NaN,NaN,NaN,NaN,NaN,27403.185000,753.785000,25296.576000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,122.372450,-1.973750,NaN,NaN,NaN,NaN,NaN,50912.640500,1802.264500,39005.096500
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,129.551000,1.597500,NaN,NaN,NaN,NaN,NaN,97056.749000,10063.228000,235028.231000

In [96]:
# Check ports describe
ports.describe(include="all")

,Name,Province,UNLCODE,Latitude,Longitude,VesselInPort,ExpectedArrival,RecentPortCalls,Type
count,74,74,74,74.000000,74.000000,74.000000,74.000000,74.00000,74
unique,74,7,40,NaN,NaN,NaN,NaN,NaN,4
top,JAMPEA,MALUKU,-,NaN,NaN,NaN,NaN,NaN,PORT
freq,1,18,35,NaN,NaN,NaN,NaN,NaN,57
mean,NaN,NaN,NaN,-2.411132,124.629134,3.148649,2.000000,4.27027,NaN
std,NaN,NaN,NaN,2.700935,3.944202,7.289855,6.333213,10.06186,NaN
min,NaN,NaN,NaN,-8.079400,119.362800,0.000000,0.000000,0.00000,NaN
25%,NaN,NaN,NaN,-4.314100,121.071725,0.000000,0.000000,0.00000,NaN
50%,NaN,NaN,NaN,-2.857850,123.714950,0.000000,0.000000,0.00000,NaN
75%,NaN,NaN,NaN,-0.282675,127.661000,2.000000,1.000000,2.00000,NaN
max,NaN,NaN,NaN,4.000000,134.211500,40.000000,50.000000,55.00000,NaN

In [97]:
# Check missing data
mines.isnull().sum()

Kecamatan                             0
Kabupaten                             0
Nama objek                            0
Nomor Lokasi Keterdapatan             0
Komoditi                              0
Kode Unsur                            0
Kelompok Mineral Logam                0
Lokasi Keterdapatan                   0
Provinsi                              0
Status Penyelidikan Mineral Logam     0
Bijih Terbukti (Ton)                  0
Logam Terbukti (Ton)                  0
keteragan                             0
acuan                                 0
objectid                              0
longitude                             0
latitude                              0
Jenis Izin                            0
Lokasi Tambang                        0
Luas Wilayah                          0
Tanggal Berakhir SK                   0
Tanggal Berlaku SK                    0
Mine_port(meter)                     29
Mine_road(meter)                     29
Mine_Smelter(meter)                  29
dtype: int64

In [98]:
ports.isnull().sum()

Name               0
Province           0
UNLCODE            0
Latitude           0
Longitude          0
VesselInPort       0
ExpectedArrival    0
RecentPortCalls    0
Type               0
dtype: int64

In [99]:
# Check duplicate data
mines.duplicated().sum()

np.int64(0)

In [100]:
ports.duplicated().sum()

np.int64(0)

DATA CLEANING

In [101]:
# Clean the column
mines.columns = mines.columns.str.strip()
ports.columns = ports.columns.str.strip()

In [102]:
# Cleaning mine number column
big_number_cols = [
    "Bijih Terbukti (Ton)",
    "Logam Terbukti (Ton)"
]

for col in big_number_cols:
    mines[col] = (
        mines[col]
        .astype(str)
        .str.replace(".", "", regex=False)
        .str.replace(",", ".", regex=False)
    )

    mines[col] = pd.to_numeric(
        mines[col],
        errors="coerce"
    )

In [103]:
# Cleaning the port number column
coord_cols = [
    "longitude",
    "latitude"
]

for col in coord_cols:
    mines[col] = pd.to_numeric(
        mines[col],
        errors="coerce"
    )

In [104]:
port_num_cols = [
    "Latitude",
    "Longitude",
    "VesselInPort",
    "ExpectedArrival",
    "RecentPortCalls"
]

for col in port_num_cols:
    ports[col] = pd.to_numeric(
        ports[col],
        errors="coerce"
    )

In [105]:
# Distance columns
distance_cols = [
    "Mine_port(meter)",
    "Mine_road(meter)",
    "Mine_Smelter(meter)",
    "Luas Wilayah"
]

for col in distance_cols:
    mines[col] = pd.to_numeric(
        mines[col],
        errors="coerce"
    )

In [106]:
# Cleaning date
date_cols = [
    "Tanggal Berakhir SK",
    "Tanggal Berlaku SK"
]

for col in date_cols:
    mines[col] = pd.to_datetime(
        mines[col],
        errors="coerce"
    )

/tmp/ipykernel_3911/1041146796.py:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  mines[col] = pd.to_datetime(

In [107]:
# Check data
print(mines.head())
print(ports.head())

   Kecamatan   Kabupaten                            Nama objek  \
0     Malili  Luwu Timur  Nikel Desa Harapan dan Desa Pongkeru
1     Towuti  Luwu Timur               Nikel Limonite Sorowako
2  Wasuponda  Luwu Timur              Nikel Soroako-Petea HPAL
3     Malili  Luwu Timur                            Nikel Ussu
4     Malili  Luwu Timur  Nikel Blok Pongkeru dan Blok Harapan

  Nomor Lokasi Keterdapatan Komoditi Kode Unsur      Kelompok Mineral Logam  \
0               283.000.000    Nikel         Ni  Logam Besi dan Paduan Besi
1               281.000.000    Nikel         Ni  Logam Besi dan Paduan Besi
2             1.921.000.000    Nikel         Ni  Logam Besi dan Paduan Besi
3             2.136.000.000    Nikel         Ni  Logam Besi dan Paduan Besi
4             2.816.000.000    Nikel         Ni  Logam Besi dan Paduan Besi

              Lokasi Keterdapatan          Provinsi  \
0  Desa Harapan dan Desa Pongkeru  Sulawesi Selatan
1               Limonite Sorowako  Sulawesi Selatan
2              Soroako-Petea HPAL  Sulawesi Selatan
3                            Ussu  Sulawesi Selatan
4  Blok Pongkeru dan Blok Harapan  Sulawesi Selatan

  Status Penyelidikan Mineral Logam  ...  longitude  latitude Jenis Izin  \
0                  Operasi Produksi  ...    121.153   -2.7880        IUP
1                        Eksplorasi  ...    121.386   -2.6170       IUPK
2                        Eksplorasi  ...    121.242   -2.6420       IUPK
3                  Operasi Produksi  ...    121.075   -2.5710        IUP
4                  Operasi Produksi  ...    121.153   -2.7885        IUP

                                    Lokasi Tambang  Luas Wilayah  \
0           Desa Harapan Kec Malili Kab Luwu Timur        2660.0
1  Blok Soroako. Kab. Luwu timur dan Kab. Morowali       70566.0
2  Blok Soroako. Kab. Luwu timur dan Kab. Morowali       70566.0
3           Desa Ussu, Kec. Malili, Kab.Luwu Timur        1419.0
4            Desa Harapan dan Pongkeru. Kec malili         303.0

   Tanggal Berakhir SK  Tanggal Berlaku SK Mine_port(meter) Mine_road(meter)  \
0           2029-11-03                 NaT        10999.274          427.609
1                  NaT                 NaT              NaN              NaN
2                  NaT                 NaT              NaN              NaN
3           2031-04-18          2011-04-18         7801.659         1707.929
4           2031-09-17          2021-09-10        11026.502          449.858

   Mine_Smelter(meter)
0            34735.389
1                  NaN
2                  NaN
3            33707.756
4            34773.727

[5 rows x 25 columns]
               Name          Province UNLCODE  Latitude  Longitude  \
0            JAMPEA  SULAWESI SELATAN       -   -7.0581   120.6100
1           BENTENG  SULAWESI SELATAN       -   -6.1166   120.4512
2     MAKASSAR ANCH  SULAWESI SELATAN       -   -5.1195   119.3628
3          MAKASSAR  SULAWESI SELATAN   IDMAK   -5.1236   119.4177
4  BIRINGKASSI ANCH  SULAWESI SELATAN       -   -4.8226   119.4630

   VesselInPort  ExpectedArrival  RecentPortCalls       Type
0             0                0                0      PORT
1             0                0                0       PORT
2            17                0               22  ANCHORAGE
3            29               13               29       PORT
4             9                0                3  ANCHORAGE

DATA VALIDATION

In [108]:
mines.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264 entries, 0 to 263
Data columns (total 25 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Kecamatan                          264 non-null    object
 1   Kabupaten                          264 non-null    object
 2   Nama objek                         264 non-null    object
 3   Nomor Lokasi Keterdapatan          264 non-null    object
 4   Komoditi                           264 non-null    object
 5   Kode Unsur                         264 non-null    object
 6   Kelompok Mineral Logam             264 non-null    object
 7   Lokasi Keterdapatan                264 non-null    object
 8   Provinsi                           264 non-null    object
 9   Status Penyelidikan Mineral Logam  264 non-null    object
 10  Bijih Terbukti (Ton)               264 non-null    int64
 11  Logam Terbukti (Ton)               264 non-null    int64
 12  keteragan                          264 non-null    object
 13  acuan                              264 non-null    object
 14  objectid                           264 non-null    int64
 15  longitude                          264 non-null    float64
 16  latitude                           264 non-null    float64
 17  Jenis Izin                         264 non-null    object
 18  Lokasi Tambang                     264 non-null    object
 19  Luas Wilayah                       262 non-null    float64
 20  Tanggal Berakhir SK                56 non-null     datetime64[ns]
 21  Tanggal Berlaku SK                 61 non-null     datetime64[ns]
 22  Mine_port(meter)                   235 non-null    float64
 23  Mine_road(meter)                   235 non-null    float64
 24  Mine_Smelter(meter)                235 non-null    float64
dtypes: datetime64[ns](2), float64(6), int64(3), object(14)
memory usage: 51.7+ KB

In [109]:
mines.describe()

,Bijih Terbukti (Ton),Logam Terbukti (Ton),objectid,longitude,latitude,Luas Wilayah,Tanggal Berakhir SK,Tanggal Berlaku SK,Mine_port(meter),Mine_road(meter),Mine_Smelter(meter)
count,2.640000e+02,2.640000e+02,264.000000,264.000000,264.000000,262.000000,56,61,235.000000,235.000000,235.000000
mean,5.403553e+07,9.614298e+09,1501.420455,122.993081,-2.746815,4614.563435,2029-10-06 20:34:17.142857216,2015-09-25 05:54:05.901639424,31658.286136,1486.749685,33301.765911
min,0.000000e+00,0.000000e+00,1291.000000,120.915200,-5.436000,100.000000,1930-04-22 00:00:00,2008-11-14 00:00:00,2538.236000,1.374000,662.173000
25%,0.000000e+00,0.000000e+00,1423.750000,121.701000,-3.826050,339.250000,2029-11-26 12:00:00,2012-04-23 00:00:00,11561.917000,231.589500,9756.476500
50%,5.725800e+06,3.958500e+04,1511.500000,122.226850,-3.213050,1216.600000,2031-04-24 12:00:00,2015-09-02 00:00:00,27403.185000,753.785000,25296.576000
75%,3.480630e+07,7.097665e+07,1588.500000,122.372450,-1.973750,3450.000000,2032-04-23 00:00:00,2019-09-19 00:00:00,50912.640500,1802.264500,39005.096500
max,2.694000e+09,4.561060e+11,1666.000000,129.551000,1.597500,70566.000000,2037-09-14 00:00:00,2024-11-19 00:00:00,97056.749000,10063.228000,235028.231000
std,2.170938e+08,4.717177e+10,104.607111,2.350677,1.651339,11501.108130,NaN,NaN,21328.000584,1970.884078,38111.731611

In [110]:
mines.head()

,Kecamatan,Kabupaten,Nama objek,Nomor Lokasi Keterdapatan,Komoditi,Kode Unsur,Kelompok Mineral Logam,Lokasi Keterdapatan,Provinsi,Status Penyelidikan Mineral Logam,...,longitude,latitude,Jenis Izin,Lokasi Tambang,Luas Wilayah,Tanggal Berakhir SK,Tanggal Berlaku SK,Mine_port(meter),Mine_road(meter),Mine_Smelter(meter)
0,Malili,Luwu Timur,Nikel Desa Harapan dan Desa Pongkeru,283.000.000,Nikel,Ni,Logam Besi dan Paduan Besi,Desa Harapan dan Desa Pongkeru,Sulawesi Selatan,Operasi Produksi,...,121.153,-2.7880,IUP,Desa Harapan Kec Malili Kab Luwu Timur,2660.0,2029-11-03,NaT,10999.274,427.609,34735.389
1,Towuti,Luwu Timur,Nikel Limonite Sorowako,281.000.000,Nikel,Ni,Logam Besi dan Paduan Besi,Limonite Sorowako,Sulawesi Selatan,Eksplorasi,...,121.386,-2.6170,IUPK,Blok Soroako. Kab. Luwu timur dan Kab. Morowali,70566.0,NaT,NaT,NaN,NaN,NaN
2,Wasuponda,Luwu Timur,Nikel Soroako-Petea HPAL,1.921.000.000,Nikel,Ni,Logam Besi dan Paduan Besi,Soroako-Petea HPAL,Sulawesi Selatan,Eksplorasi,...,121.242,-2.6420,IUPK,Blok Soroako. Kab. Luwu timur dan Kab. Morowali,70566.0,NaT,NaT,NaN,NaN,NaN
3,Malili,Luwu Timur,Nikel Ussu,2.136.000.000,Nikel,Ni,Logam Besi dan Paduan Besi,Ussu,Sulawesi Selatan,Operasi Produksi,...,121.075,-2.5710,IUP,"Desa Ussu, Kec. Malili, Kab.Luwu Timur",1419.0,2031-04-18,2011-04-18,7801.659,1707.929,33707.756
4,Malili,Luwu Timur,Nikel Blok Pongkeru dan Blok Harapan,2.816.000.000,Nikel,Ni,Logam Besi dan Paduan Besi,Blok Pongkeru dan Blok Harapan,Sulawesi Selatan,Operasi Produksi,...,121.153,-2.7885,IUP,Desa Harapan dan Pongkeru. Kec malili,303.0,2031-09-17,2021-09-10,11026.502,449.858,34773.727

In [111]:
mines[["latitude", "longitude"]].describe()

         latitude   longitude
count  264.000000  264.000000
mean    -2.746815  122.993081
std      1.651339    2.350677
min     -5.436000  120.915200
25%     -3.826050  121.701000
50%     -3.213050  122.226850
75%     -1.973750  122.372450
max      1.597500  129.551000

In [112]:
ports.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             74 non-null     object
 1   Province         74 non-null     object
 2   UNLCODE          74 non-null     object
 3   Latitude         74 non-null     float64
 4   Longitude        74 non-null     float64
 5   VesselInPort     74 non-null     int64
 6   ExpectedArrival  74 non-null     int64
 7   RecentPortCalls  74 non-null     int64
 8   Type             74 non-null     object
dtypes: float64(2), int64(3), object(4)
memory usage: 5.3+ KB

In [113]:
ports.describe()

        Latitude   Longitude  VesselInPort  ExpectedArrival  RecentPortCalls
count  74.000000   74.000000     74.000000        74.000000         74.00000
mean   -2.411132  124.629134      3.148649         2.000000          4.27027
std     2.700935    3.944202      7.289855         6.333213         10.06186
min    -8.079400  119.362800      0.000000         0.000000          0.00000
25%    -4.314100  121.071725      0.000000         0.000000          0.00000
50%    -2.857850  123.714950      0.000000         0.000000          0.00000
75%    -0.282675  127.661000      2.000000         1.000000          2.00000
max     4.000000  134.211500     40.000000        50.000000         55.00000

SAVE DATA

In [ ]:
# Save mines data
mines.to_csv(
    f"{BASE_PATH}/cleaned_mines.csv",
    index=False
)

In [ ]:
# Save port data
ports.to_csv(
    f"{BASE_PATH}/cleaned_ports.csv",
    index=False
)